export type StackGroup = {
  title: string;
  caption: string;
  items: string[];
};

export const stack: StackGroup[] = [
  {
    title: "Languages",
    caption: "What I think in",
    items: ["Python", "TypeScript", "JavaScript", "C++", "Go", "Java", "SQL", "Bash", "HTML", "CSS"],
  },
  {
    title: "Frontend",
    caption: "Pixel-precise, motion-rich UIs",
    items: [
      "Next.js 14 (App Router)",
      "React 18",
      "Tailwind CSS",
      "Framer Motion",
      "GSAP",
      "Lenis",
      "shadcn/ui",
      "Radix UI",
      "Zustand",
      "TanStack Query",
      "React Hook Form",
      "D3.js",
      "Recharts",
      "Three.js",
      "Lucide",
    ],
  },
  {
    title: "Backend",
    caption: "APIs, real-time and microservices",
    items: [
      "Node.js",
      "Express",
      "NestJS",
      "FastAPI",
      "Flask",
      "Django",
      "Socket.IO",
      "GraphQL",
      "gRPC",
      "REST",
      "tRPC",
      "Celery",
      "Node-cron",
    ],
  },
  {
    title: "Databases & Storage",
    caption: "OLTP, vector, cache, object",
    items: [
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "Pinecone",
      "ChromaDB",
      "Weaviate",
      "Prisma",
      "Mongoose",
      "Drizzle ORM",
      "AWS S3",
      "Supabase",
    ],
  },
  {
    title: "AI / ML",
    caption: "Models, training, inference",
    items: [
      "PyTorch",
      "TensorFlow / Keras",
      "scikit-learn",
      "Hugging Face Transformers",
      "Hugging Face Datasets",
      "PEFT / LoRA",
      "TRL (GRPO / PPO / DPO)",
      "vLLM",
      "Unsloth",
      "Accelerate",
      "ResNet",
      "CatBoost",
      "XGBoost",
      "LightGBM",
      "OpenCV",
      "NLTK",
      "spaCy",
      "SymPy",
      "NumPy",
      "Pandas",
      "SciPy",
    ],
  },
  {
    title: "Agentic AI / LLMs",
    caption: "Agents, RAG, tool-use",
    items: [
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "OpenAI SDK",
      "Anthropic SDK",
      "Groq",
      "Google Gemini",
      "Ollama",
      "AWS Textract",
      "Vector RAG",
      "Hybrid RAG",
      "Function Calling",
      "Multi-agent Planners",
    ],
  },
  {
    title: "MLOps / DevOps",
    caption: "Ship, run, observe",
    items: [
      "Docker",
      "Kubernetes",
      "k3s",
      "Helm",
      "Terraform",
      "GitHub Actions",
      "Jenkins",
      "ArgoCD",
      "AWS (S3, Lambda, EC2, EKS, Textract)",
      "GCP (Earth Engine, Cloud Run)",
      "Hetzner",
      "Vercel",
      "Render",
      "Railway",
      "Hugging Face Spaces",
      "MLflow",
      "Weights & Biases",
      "DVC",
    ],
  },
  {
    title: "Observability / SRE",
    caption: "Visibility under load",
    items: [
      "Prometheus",
      "Loki",
      "Grafana",
      "Alertmanager",
      "Chaos Mesh",
      "OpenTelemetry",
      "Jaeger",
      "Sentry",
      "PagerDuty (concepts)",
    ],
  },
  {
    title: "Distributed Systems",
    caption: "Causality, consensus, scale",
    items: [
      "Kafka",
      "RabbitMQ",
      "Lamport / Vector Clocks",
      "Raft",
      "Microservices",
      "Event-driven Architecture",
      "CQRS",
      "Saga Pattern",
    ],
  },
  {
    title: "Auth & Security",
    caption: "Locks that hold",
    items: ["JWT", "OAuth 2.0", "Clerk", "NextAuth.js", "bcrypt", "Argon2", "RBAC", "CORS hardening", "Rate limiting"],
  },
  {
    title: "Tooling",
    caption: "Day-to-day battle gear",
    items: ["Git", "GitHub", "VS Code", "Vim", "Linux", "Jupyter", "Kaggle", "Postman", "Insomnia", "Figma"],
  },
  {
    title: "CP & Math",
    caption: "Foundations",
    items: [
      "Codeforces: Specialist",
      "Competitive Programming",
      "Data Structures & Algorithms",
      "Discrete Math",
      "Linear Algebra",
      "Probability & Stats",
      "Optimisation",
    ],
  },
];

// flat list for marquee
export const flatStack = Array.from(new Set(stack.flatMap((g) => g.items)));
